%% Barrett et al. (2012) NeuroImage

SIM_LIST = {...
    'flow_volume_loop',...    
    'mandeville1999_6s',...
    'mandeville1999_30s',...
    '1_second',...
    '10_seconds',...
    '30_seconds',...
    };

FIG_LIST = {...
    'topdown_combined',...
    'bottomup_combined',...
    };

DefaultIn = [];
OverrideIn = [];

figFormats = [];
figNames = [];

default_simulations(DefaultIn, SIM_LIST, FIG_LIST, figFormats, figNames, ...
    OverrideIn);
